---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - test/minitest/utils/let_test.rb

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
