---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/**/*

Style/GlobalVars:
  Exclude:
    - test/minitest/utils/let_test.rb

Minitest/UselessAssertion:
  Enabled: false
