#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["MT_RUNNER"] = "true"
require_relative "../lib/minitest/utils/cli"
Minitest::Utils::CLI.loaded_via_bundle_exec = ENV.key?("BUNDLER_VERSION")
Minitest::Utils::CLI.new(ARGV.dup).start
